# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

# Ref: https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'build: update pre-commit hooks'
  autoupdate_schedule: monthly
  skip: [licensecheck] # does not run on pre-commit.ci, due to sqlite error, runs locally

repos:
  # Ref: https://pre-commit.com/#meta-hooks
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
  hooks:
  - id: check-ast
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: a362181620503bf7446d3f5c98cc004b9403543d  # frozen: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 6604011085496f01169cafa8b0fc5462b81e1813  # frozen: 0.27.3
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 15ce99ba02863ca8df16ca727714e6c7de11f9a4  # frozen: 1.5.3
  hooks:
  - id: pyproject-fmt

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: d7c4946c7c152163ce34efe35be4e1015d053edd  # frozen: v0.1.8
  hooks:
  - id: ruff
    args: [--fix, --show-fixes, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 4daa14b20c0f48f472528c2b5f5bca28a18a7ce0  # frozen: v1.7.1
  hooks:
  - id: mypy
    args: [--config-file=pyproject.toml]
    additional_dependencies:
    - httpx==0.25.2
    - lxml-stubs==0.4.0
    exclude: tests

- repo: https://github.com/scientific-python/cookie
  rev: acb56111d31a9902188dfdb21963ad31490dd1b8  # frozen: 2023.11.17
  hooks:
  - id: sp-repo-review

- repo: https://github.com/crate-ci/typos
  rev: 155838b12f73c05291c7346c21a2510a92ba0bcf  # frozen: v1.16.25
  hooks:
  - id: typos
    args: [--force-exclude] # default is [--write-changes, --force-exclude]
    exclude: tests/cassettes

- repo: https://github.com/FHPythonUtils/LicenseCheck/
  rev: 0d58138937fb0c67733100935727a99ef8cd9bc5  # frozen: 2023.5.2
  hooks:
  - id: licensecheck

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: 09de2d8736611042feeff83688b5b5b35d459c7c  # frozen: v3.0.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
