# pre-commit
# Ref: https://pre-commit.com/#usage
# ------------------------------------------------------------------------------

repos:
  # Ref: https://pre-commit.com/#meta-hooks
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-ast
  - id: check-toml
  - id: check-xml
    exclude: tests/data/ListRecordsBroken.xml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.0
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 1.2.0
  hooks:
  - id: pyproject-fmt

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.1
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/FHPythonUtils/LicenseCheck/
  rev: 2023.5.1
  hooks:
  - id: licensecheck

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
