"""This file was generated by xsdata, v24.5, on 2024-05-17 16:05:33

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from oaipmh_scythe.models.marcxml.models import (
    Collection,
    CollectionType,
    ControlFieldType,
    DataFieldType,
    LeaderFieldType,
    Record,
    RecordType,
    RecordTypeType,
    SubfieldatafieldType,
)

__all__ = [
    "Collection",
    "CollectionType",
    "ControlFieldType",
    "DataFieldType",
    "LeaderFieldType",
    "Record",
    "RecordType",
    "RecordTypeType",
    "SubfieldatafieldType",
]
