"""This file was generated by xsdata, v24.5, on 2024-05-17 15:55:14

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from src.oaipmh_scythe.models.oai_datacite.models import (
    OaiDatacite,
    RootType,
)

__all__ = [
    "OaiDatacite",
    "RootType",
]
