"""This file was generated by xsdata, v24.5, on 2024-05-17 15:55:14

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from __future__ import annotations

from dataclasses import dataclass, field

__NAMESPACE__ = "http://schema.datacite.org/oai/oai-1.1/"


@dataclass(slots=True)
class RootType:
    """
    Attributes:
        datacentre_symbol: The symbol of the datacentre that registered this record.
        schema_version: The estimated DataCite Metadata Scheme version that this record adheres to.
        payload: The complete, unaltered metadata of this record.
    """

    class Meta:
        name = "rootType"

    datacentre_symbol: None | str = field(
        default=None,
        metadata={
            "name": "datacentreSymbol",
            "type": "Element",
            "namespace": "http://schema.datacite.org/oai/oai-1.1/",
            "required": True,
        },
    )
    schema_version: None | object = field(
        default=None,
        metadata={
            "name": "schemaVersion",
            "type": "Element",
            "namespace": "http://schema.datacite.org/oai/oai-1.1/",
        },
    )
    payload: None | object = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://schema.datacite.org/oai/oai-1.1/",
        },
    )


@dataclass(slots=True)
class OaiDatacite(RootType):
    class Meta:
        name = "oai_datacite"
        namespace = "http://schema.datacite.org/oai/oai-1.1/"
