# mkdocs
# Ref: https://www.mkdocs.org/user-guide/configuration/
# ------------------------------------------------------------------------------

site_name: oaipmh-scythe
site_description: A Scythe for harvesting OAI-PMH repositories.
repo_name: afuetterer/oaipmh-scythe
repo_url: https://github.com/afuetterer/oaipmh-scythe
docs_dir: src
edit_uri: edit/main/docs/

nav:
- Home: index.md
- Tutorial: tutorial.md
- OAI-PMH Primer: oaipmh.md
- Harvesting other Metadata Formats than OAI-DC: customizing.md
- API:
  - The Scythe Client: api/client.md
  - Working with OAI Responses: api/response.md
  - Iterating over OAI Items: api/iterator.md
  - Classes for OAI Items: api/models.md
- Meta:
  - Contributor Guide: contributing.md
  - Changelog: changelog.md
  - License: license.md

theme:
  name: material
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - navigation.footer
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins:
- search
- include-markdown
- mkdocstrings:
    default_handler: python

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
