# mkdocs
# Ref: https://www.mkdocs.org/user-guide/configuration/
# ------------------------------------------------------------------------------

site_name: oaipmh-scythe
site_description: A Scythe for harvesting OAI-PMH repositories.
repo_name: afuetterer/oaipmh-scythe
repo_url: https://github.com/afuetterer/oaipmh-scythe
docs_dir: src
edit_uri: edit/main/docs/
watch:
- ../src

nav:
- Home: index.md
- Tutorial: tutorial.md
- OAI-PMH Primer: oaipmh.md
- Harvesting other Metadata Formats than OAI-DC: customizing.md
- API:
  - Client: api/client.md
  - Iterator: api/iterator.md
  - Models: api/models.md
  - Response: api/response.md
  - Utils: api/utils.md
  - Exceptions: api/exceptions.md
- Meta:
  - Contributor Guide: contributing.md
  - Changelog: changelog.md
  - License: license.md

theme:
  name: material
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - navigation.footer
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins:
- search
- include-markdown
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
        - ../src
        options:
          show_root_heading: false
          show_root_toc_entry: false
        import:
        - https://docs.python.org/3/objects.inv

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
