name: Docs

on:
  release:
    types: [created]
  workflow_call:
  # run manually from actions tab
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  docs:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Set up Python 3.12
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.12'
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        key: docs-${{ hashFiles('pyproject.toml') }}
        path: ~/.cache/pip
    - name: Install pre-requisites (e.g. hatch)
      run: python -m pip install --require-hashes --requirement=.github/requirements/ci.txt
    - run: hatch run docs:build
    - run: hatch run docs:deploy
      if: contains(fromJSON('["release", "workflow_dispatch"]'), github.event_name)
