name: Docs

on:
  release:
    types: [created]
  workflow_call:
  # run manually from actions tab
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

permissions:
  contents: read

jobs:
  docs:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0 # fetch all commits and branches
    - name: Set up Python 3.12
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.12'
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: docs-${{ hashFiles('pyproject.toml') }}
        path: ~/.cache/pip
    - name: Install pre-requisites (e.g. hatch)
      run: python -m pip install --require-hashes --requirement=requirements/ci
    - run: hatch run docs:build
      if: github.event_name == 'pull_request'
    - run: |
        hatch version
        hatch run docs:deploy
      if: contains(fromJSON('["release", "workflow_dispatch"]'), github.event_name)
      env:
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
