name: Docs

on:
  release:
    types: [created]
  workflow_call:

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1

permissions:
  contents: read

jobs:
  docs:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11   # v3.6.0
    - name: Set up Python 3.12
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c   # v5.0.0
      with:
        python-version: '3.12'
    - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84   # v3.3.2
      with:
        key: docs-${{ hashFiles('pyproject.toml') }}
        path: ~/.cache/pip
    - run: python -m pip install --constraint=.github/workflows/constraints.txt pip setuptools wheel hatch
    - run: hatch run docs:build
    - run: hatch run docs:deploy
      if: github.event_name == 'release'
