name: Docs

on:
  release:
    types: [created]
  workflow_call:
  # run manually from actions tab
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

permissions:
  contents: read

jobs:
  docs:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0 # fetch all commits and branches
    - name: Set up Python 3.13
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.13'
    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: docs-${{ hashFiles('pyproject.toml') }}
        path: ~/.cache/pip
    - name: Install pre-requisites (e.g. hatch)
      run: python -m pip install --require-hashes --requirement=requirements/ci
    - run: hatch run docs:build
      if: github.event_name == 'pull_request'
    - run: |
        hatch version
        hatch run docs:deploy
      if: contains(fromJSON('["release", "workflow_dispatch"]'), github.event_name)
      env:
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
