name: Label

on:
  push:
    branches:
    - main
    paths:
    - .github/labels.yml
    - .github/workflows/label.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  label:
    permissions:
      issues: write
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Run GitHub Labeler
      uses: crazy-max/ghaction-github-labeler@de749cf181958193cb7debf1a9c5bb28922f3e1b # v5.0.0
