name: Label

on:
  push:
    branches:
    - main
    paths:
    - .github/labels.yml
    - .github/workflows/label.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  label:
    permissions:
      issues: write
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Run GitHub Labeler
      uses: crazy-max/ghaction-github-labeler@de749cf181958193cb7debf1a9c5bb28922f3e1b # v5.0.0
