name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  release:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-22.04
    needs:
    - test
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0 # get all commits and tags
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
    - name: Create semantic release
      id: release
      uses: python-semantic-release/python-semantic-release@c1059f5b90895f75bde3d088bdc69e734e983535 # v8.7.0
      with:
        # allows for python-semantic-release to push to protected main branch
        github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        git_committer_name: github-actions[bot]
        git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com
    - name: Publish package to GitHub Release
      uses: python-semantic-release/upload-to-gh-release@0f96c02a48278aff14251e9f1a0d73122a8c638b
      if: ${{ steps.release.outputs.released }} == 'true'
      with:
        github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
