name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

# Set permissions at the job level.
permissions: {}

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  release:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs:
    - test
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0 # get all commits and tags
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
    - name: Create semantic release
      uses: python-semantic-release/python-semantic-release@4d4cb0ab842247caea1963132c242c62aab1e4d5 # v10.4.1
      with:
        # allows for python-semantic-release to push to protected main branch
        github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
