name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-22.04
    needs:
    - lint
    - test
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11   # v4.1.1
      with:
        fetch-depth: 0 # get all commits and tags
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
    - name: Create semantic release
      uses: python-semantic-release/python-semantic-release@d38d71ef2ae2b3c34066557ddb822385c1730c7f   # v8.3.0
      with:
        # allows for python-semantic-release to push to protected main branch
        github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        git_committer_name: github-actions[bot]
        git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com
    - name: Upload wheel and sdist
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: dist
        path: |
          dist/*.tar.gz
          dist/*.whl
        if-no-files-found: error
        retention-days: 1

  publish:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-22.04
    needs:
    - release
    environment:
      name: publish
      url: https://test.pypi.org/p/oaipmh-scythe/
    permissions:
      id-token: write  # needed for trusted publishing
    steps:
    - name: Download wheel and sdist
      uses: actions/download-artifact@v3
      with:
        name: dist
    - name: Display structure of downloaded files
      run: ls -R
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e   # v1.8.10
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
