name: Publish package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch: # run manually from actions tab

# Set permissions at the job level.
permissions: {}

jobs:
  build:
    name: Build the package
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    permissions:
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
      with:
        attest-build-provenance-github: 'true'
  upload:
    name: Upload package distributions to GitHub Releases
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download package built by build job
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: Packages
        path: dist
    - name: Publish package distributions to GitHub Releases
      uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
      with:
        files: dist/*
  publish:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    needs: build
    environment: publish
    permissions:
      id-token: write
    steps:
    - name: Download package built by build job
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: Packages
        path: dist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

  docs:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Set up just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0 # fetch all commits and branches
    - name: Set up uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        python-version: '3.13'
        enable-cache: true
        prune-cache: false
        cache-suffix: docs
    - run: just sync-docs
    - run: just docs-deploy
      env:
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
