name: Publish package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-22.04
    environment: publish
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.12'
        cache: pip
    - name: Install pre-requisites (e.g. hatch)
      run: python -m pip install --require-hashes --requirement=.github/requirements/ci.txt
    - run: python -m build --installer=uv
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
