name: Publish package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch: # run manually from actions tab

# Set permissions at the job level.
permissions: {}

jobs:
  build:
    name: Build the package
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    permissions:
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: hynek/build-and-inspect-python-package@f01e4d047aadcc0c054c95ec9900da3ec3fc7a0f # v2.10.0
      with:
        attest-build-provenance-github: 'true'
  upload:
    name: Upload package distributions to GitHub Releases
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download package built by build job
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: Packages
        path: dist
    - name: Publish package distributions to GitHub Releases
      uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # v2.0.9
      with:
        files: dist/*
  publish:
    # disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    needs: build
    environment: publish
    permissions:
      id-token: write
    steps:
    - name: Download package built by build job
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: Packages
        path: dist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@fb13cb306901256ace3dab689990e13a5550ffaa # v1.11.0
